package com.pc.bean;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedbikeArea.proto

public final class SharedbikeAreaOuterClass {
  private SharedbikeAreaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SharedbikeAreaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SharedbikeArea)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 区域id
     * </pre>
     *
     * <code>required uint32 areaId = 1;</code>
     * @return Whether the areaId field is set.
     */
    boolean hasAreaId();
    /**
     * <pre>
     * 区域id
     * </pre>
     *
     * <code>required uint32 areaId = 1;</code>
     * @return The areaId.
     */
    int getAreaId();

    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 经度
     * </pre>
     *
     * <code>required double lng = 3;</code>
     * @return Whether the lng field is set.
     */
    boolean hasLng();
    /**
     * <pre>
     * 经度
     * </pre>
     *
     * <code>required double lng = 3;</code>
     * @return The lng.
     */
    double getLng();

    /**
     * <pre>
     * 纬度
     * </pre>
     *
     * <code>required double lat = 4;</code>
     * @return Whether the lat field is set.
     */
    boolean hasLat();
    /**
     * <pre>
     * 纬度
     * </pre>
     *
     * <code>required double lat = 4;</code>
     * @return The lat.
     */
    double getLat();

    /**
     * <pre>
     * 面积
     * </pre>
     *
     * <code>required double size = 5;</code>
     * @return Whether the size field is set.
     */
    boolean hasSize();
    /**
     * <pre>
     * 面积
     * </pre>
     *
     * <code>required double size = 5;</code>
     * @return The size.
     */
    double getSize();

    /**
     * <pre>
     * 类型
     * </pre>
     *
     * <code>required uint32 type = 6;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     * 类型
     * </pre>
     *
     * <code>required uint32 type = 6;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     * 区域最大车辆数
     * </pre>
     *
     * <code>required uint32 maxNum = 7;</code>
     * @return Whether the maxNum field is set.
     */
    boolean hasMaxNum();
    /**
     * <pre>
     * 区域最大车辆数
     * </pre>
     *
     * <code>required uint32 maxNum = 7;</code>
     * @return The maxNum.
     */
    int getMaxNum();

    /**
     * <pre>
     * 区域当前自行车数量
     * </pre>
     *
     * <code>required uint32 num = 8;</code>
     * @return Whether the num field is set.
     */
    boolean hasNum();
    /**
     * <pre>
     * 区域当前自行车数量
     * </pre>
     *
     * <code>required uint32 num = 8;</code>
     * @return The num.
     */
    int getNum();

    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>required string remark = 9;</code>
     * @return Whether the remark field is set.
     */
    boolean hasRemark();
    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>required string remark = 9;</code>
     * @return The remark.
     */
    String getRemark();
    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>required string remark = 9;</code>
     * @return The bytes for remark.
     */
    com.google.protobuf.ByteString
        getRemarkBytes();
  }
  /**
   * <pre>
   * 4、停车区域信息
   * </pre>
   *
   * Protobuf type {@code SharedbikeArea}
   */
  public static final class SharedbikeArea extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SharedbikeArea)
      SharedbikeAreaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SharedbikeArea.newBuilder() to construct.
    private SharedbikeArea(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SharedbikeArea() {
      name_ = "";
      remark_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SharedbikeArea();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SharedbikeArea(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              areaId_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              lng_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              lat_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              size_ = input.readDouble();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              type_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              maxNum_ = input.readUInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              num_ = input.readUInt32();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              remark_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SharedbikeAreaOuterClass.internal_static_SharedbikeArea_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SharedbikeAreaOuterClass.internal_static_SharedbikeArea_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SharedbikeArea.class, Builder.class);
    }

    private int bitField0_;
    public static final int AREAID_FIELD_NUMBER = 1;
    private int areaId_;
    /**
     * <pre>
     * 区域id
     * </pre>
     *
     * <code>required uint32 areaId = 1;</code>
     * @return Whether the areaId field is set.
     */
    @Override
    public boolean hasAreaId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 区域id
     * </pre>
     *
     * <code>required uint32 areaId = 1;</code>
     * @return The areaId.
     */
    @Override
    public int getAreaId() {
      return areaId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    @Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LNG_FIELD_NUMBER = 3;
    private double lng_;
    /**
     * <pre>
     * 经度
     * </pre>
     *
     * <code>required double lng = 3;</code>
     * @return Whether the lng field is set.
     */
    @Override
    public boolean hasLng() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 经度
     * </pre>
     *
     * <code>required double lng = 3;</code>
     * @return The lng.
     */
    @Override
    public double getLng() {
      return lng_;
    }

    public static final int LAT_FIELD_NUMBER = 4;
    private double lat_;
    /**
     * <pre>
     * 纬度
     * </pre>
     *
     * <code>required double lat = 4;</code>
     * @return Whether the lat field is set.
     */
    @Override
    public boolean hasLat() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 纬度
     * </pre>
     *
     * <code>required double lat = 4;</code>
     * @return The lat.
     */
    @Override
    public double getLat() {
      return lat_;
    }

    public static final int SIZE_FIELD_NUMBER = 5;
    private double size_;
    /**
     * <pre>
     * 面积
     * </pre>
     *
     * <code>required double size = 5;</code>
     * @return Whether the size field is set.
     */
    @Override
    public boolean hasSize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 面积
     * </pre>
     *
     * <code>required double size = 5;</code>
     * @return The size.
     */
    @Override
    public double getSize() {
      return size_;
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_;
    /**
     * <pre>
     * 类型
     * </pre>
     *
     * <code>required uint32 type = 6;</code>
     * @return Whether the type field is set.
     */
    @Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 类型
     * </pre>
     *
     * <code>required uint32 type = 6;</code>
     * @return The type.
     */
    @Override
    public int getType() {
      return type_;
    }

    public static final int MAXNUM_FIELD_NUMBER = 7;
    private int maxNum_;
    /**
     * <pre>
     * 区域最大车辆数
     * </pre>
     *
     * <code>required uint32 maxNum = 7;</code>
     * @return Whether the maxNum field is set.
     */
    @Override
    public boolean hasMaxNum() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 区域最大车辆数
     * </pre>
     *
     * <code>required uint32 maxNum = 7;</code>
     * @return The maxNum.
     */
    @Override
    public int getMaxNum() {
      return maxNum_;
    }

    public static final int NUM_FIELD_NUMBER = 8;
    private int num_;
    /**
     * <pre>
     * 区域当前自行车数量
     * </pre>
     *
     * <code>required uint32 num = 8;</code>
     * @return Whether the num field is set.
     */
    @Override
    public boolean hasNum() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 区域当前自行车数量
     * </pre>
     *
     * <code>required uint32 num = 8;</code>
     * @return The num.
     */
    @Override
    public int getNum() {
      return num_;
    }

    public static final int REMARK_FIELD_NUMBER = 9;
    private volatile Object remark_;
    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>required string remark = 9;</code>
     * @return Whether the remark field is set.
     */
    @Override
    public boolean hasRemark() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>required string remark = 9;</code>
     * @return The remark.
     */
    @Override
    public String getRemark() {
      Object ref = remark_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remark_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>required string remark = 9;</code>
     * @return The bytes for remark.
     */
    @Override
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAreaId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRemark()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, areaId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, lng_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(4, lat_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeDouble(5, size_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt32(6, type_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt32(7, maxNum_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeUInt32(8, num_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, remark_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, areaId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, lng_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, lat_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, size_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, type_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, maxNum_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, num_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, remark_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SharedbikeArea)) {
        return super.equals(obj);
      }
      SharedbikeArea other = (SharedbikeArea) obj;

      if (hasAreaId() != other.hasAreaId()) return false;
      if (hasAreaId()) {
        if (getAreaId()
            != other.getAreaId()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasLng() != other.hasLng()) return false;
      if (hasLng()) {
        if (Double.doubleToLongBits(getLng())
            != Double.doubleToLongBits(
                other.getLng())) return false;
      }
      if (hasLat() != other.hasLat()) return false;
      if (hasLat()) {
        if (Double.doubleToLongBits(getLat())
            != Double.doubleToLongBits(
                other.getLat())) return false;
      }
      if (hasSize() != other.hasSize()) return false;
      if (hasSize()) {
        if (Double.doubleToLongBits(getSize())
            != Double.doubleToLongBits(
                other.getSize())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasMaxNum() != other.hasMaxNum()) return false;
      if (hasMaxNum()) {
        if (getMaxNum()
            != other.getMaxNum()) return false;
      }
      if (hasNum() != other.hasNum()) return false;
      if (hasNum()) {
        if (getNum()
            != other.getNum()) return false;
      }
      if (hasRemark() != other.hasRemark()) return false;
      if (hasRemark()) {
        if (!getRemark()
            .equals(other.getRemark())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAreaId()) {
        hash = (37 * hash) + AREAID_FIELD_NUMBER;
        hash = (53 * hash) + getAreaId();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasLng()) {
        hash = (37 * hash) + LNG_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getLng()));
      }
      if (hasLat()) {
        hash = (37 * hash) + LAT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getLat()));
      }
      if (hasSize()) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getSize()));
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasMaxNum()) {
        hash = (37 * hash) + MAXNUM_FIELD_NUMBER;
        hash = (53 * hash) + getMaxNum();
      }
      if (hasNum()) {
        hash = (37 * hash) + NUM_FIELD_NUMBER;
        hash = (53 * hash) + getNum();
      }
      if (hasRemark()) {
        hash = (37 * hash) + REMARK_FIELD_NUMBER;
        hash = (53 * hash) + getRemark().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SharedbikeArea parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SharedbikeArea parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SharedbikeArea parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SharedbikeArea parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SharedbikeArea parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SharedbikeArea parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SharedbikeArea parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SharedbikeArea parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SharedbikeArea parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SharedbikeArea parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SharedbikeArea parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SharedbikeArea parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SharedbikeArea prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 4、停车区域信息
     * </pre>
     *
     * Protobuf type {@code SharedbikeArea}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SharedbikeArea)
        SharedbikeAreaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SharedbikeAreaOuterClass.internal_static_SharedbikeArea_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SharedbikeAreaOuterClass.internal_static_SharedbikeArea_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SharedbikeArea.class, Builder.class);
      }

      // Construct using SharedbikeAreaOuterClass.SharedbikeArea.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        areaId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lng_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        size_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        maxNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        remark_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SharedbikeAreaOuterClass.internal_static_SharedbikeArea_descriptor;
      }

      @Override
      public SharedbikeArea getDefaultInstanceForType() {
        return SharedbikeArea.getDefaultInstance();
      }

      @Override
      public SharedbikeArea build() {
        SharedbikeArea result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SharedbikeArea buildPartial() {
        SharedbikeArea result = new SharedbikeArea(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.areaId_ = areaId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.lng_ = lng_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lat_ = lat_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.size_ = size_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.maxNum_ = maxNum_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.num_ = num_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000100;
        }
        result.remark_ = remark_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SharedbikeArea) {
          return mergeFrom((SharedbikeArea)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SharedbikeArea other) {
        if (other == SharedbikeArea.getDefaultInstance()) return this;
        if (other.hasAreaId()) {
          setAreaId(other.getAreaId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLng()) {
          setLng(other.getLng());
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMaxNum()) {
          setMaxNum(other.getMaxNum());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasRemark()) {
          bitField0_ |= 0x00000100;
          remark_ = other.remark_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasAreaId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasLng()) {
          return false;
        }
        if (!hasLat()) {
          return false;
        }
        if (!hasSize()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasMaxNum()) {
          return false;
        }
        if (!hasNum()) {
          return false;
        }
        if (!hasRemark()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SharedbikeArea parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SharedbikeArea) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int areaId_ ;
      /**
       * <pre>
       * 区域id
       * </pre>
       *
       * <code>required uint32 areaId = 1;</code>
       * @return Whether the areaId field is set.
       */
      @Override
      public boolean hasAreaId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 区域id
       * </pre>
       *
       * <code>required uint32 areaId = 1;</code>
       * @return The areaId.
       */
      @Override
      public int getAreaId() {
        return areaId_;
      }
      /**
       * <pre>
       * 区域id
       * </pre>
       *
       * <code>required uint32 areaId = 1;</code>
       * @param value The areaId to set.
       * @return This builder for chaining.
       */
      public Builder setAreaId(int value) {
        bitField0_ |= 0x00000001;
        areaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 区域id
       * </pre>
       *
       * <code>required uint32 areaId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAreaId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        areaId_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>required string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private double lng_ ;
      /**
       * <pre>
       * 经度
       * </pre>
       *
       * <code>required double lng = 3;</code>
       * @return Whether the lng field is set.
       */
      @Override
      public boolean hasLng() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * 经度
       * </pre>
       *
       * <code>required double lng = 3;</code>
       * @return The lng.
       */
      @Override
      public double getLng() {
        return lng_;
      }
      /**
       * <pre>
       * 经度
       * </pre>
       *
       * <code>required double lng = 3;</code>
       * @param value The lng to set.
       * @return This builder for chaining.
       */
      public Builder setLng(double value) {
        bitField0_ |= 0x00000004;
        lng_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 经度
       * </pre>
       *
       * <code>required double lng = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLng() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lng_ = 0D;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <pre>
       * 纬度
       * </pre>
       *
       * <code>required double lat = 4;</code>
       * @return Whether the lat field is set.
       */
      @Override
      public boolean hasLat() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 纬度
       * </pre>
       *
       * <code>required double lat = 4;</code>
       * @return The lat.
       */
      @Override
      public double getLat() {
        return lat_;
      }
      /**
       * <pre>
       * 纬度
       * </pre>
       *
       * <code>required double lat = 4;</code>
       * @param value The lat to set.
       * @return This builder for chaining.
       */
      public Builder setLat(double value) {
        bitField0_ |= 0x00000008;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 纬度
       * </pre>
       *
       * <code>required double lat = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lat_ = 0D;
        onChanged();
        return this;
      }

      private double size_ ;
      /**
       * <pre>
       * 面积
       * </pre>
       *
       * <code>required double size = 5;</code>
       * @return Whether the size field is set.
       */
      @Override
      public boolean hasSize() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 面积
       * </pre>
       *
       * <code>required double size = 5;</code>
       * @return The size.
       */
      @Override
      public double getSize() {
        return size_;
      }
      /**
       * <pre>
       * 面积
       * </pre>
       *
       * <code>required double size = 5;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(double value) {
        bitField0_ |= 0x00000010;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 面积
       * </pre>
       *
       * <code>required double size = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        size_ = 0D;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 类型
       * </pre>
       *
       * <code>required uint32 type = 6;</code>
       * @return Whether the type field is set.
       */
      @Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * 类型
       * </pre>
       *
       * <code>required uint32 type = 6;</code>
       * @return The type.
       */
      @Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 类型
       * </pre>
       *
       * <code>required uint32 type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 类型
       * </pre>
       *
       * <code>required uint32 type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        onChanged();
        return this;
      }

      private int maxNum_ ;
      /**
       * <pre>
       * 区域最大车辆数
       * </pre>
       *
       * <code>required uint32 maxNum = 7;</code>
       * @return Whether the maxNum field is set.
       */
      @Override
      public boolean hasMaxNum() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * 区域最大车辆数
       * </pre>
       *
       * <code>required uint32 maxNum = 7;</code>
       * @return The maxNum.
       */
      @Override
      public int getMaxNum() {
        return maxNum_;
      }
      /**
       * <pre>
       * 区域最大车辆数
       * </pre>
       *
       * <code>required uint32 maxNum = 7;</code>
       * @param value The maxNum to set.
       * @return This builder for chaining.
       */
      public Builder setMaxNum(int value) {
        bitField0_ |= 0x00000040;
        maxNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 区域最大车辆数
       * </pre>
       *
       * <code>required uint32 maxNum = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxNum() {
        bitField0_ = (bitField0_ & ~0x00000040);
        maxNum_ = 0;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <pre>
       * 区域当前自行车数量
       * </pre>
       *
       * <code>required uint32 num = 8;</code>
       * @return Whether the num field is set.
       */
      @Override
      public boolean hasNum() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * 区域当前自行车数量
       * </pre>
       *
       * <code>required uint32 num = 8;</code>
       * @return The num.
       */
      @Override
      public int getNum() {
        return num_;
      }
      /**
       * <pre>
       * 区域当前自行车数量
       * </pre>
       *
       * <code>required uint32 num = 8;</code>
       * @param value The num to set.
       * @return This builder for chaining.
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000080;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 区域当前自行车数量
       * </pre>
       *
       * <code>required uint32 num = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000080);
        num_ = 0;
        onChanged();
        return this;
      }

      private Object remark_ = "";
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>required string remark = 9;</code>
       * @return Whether the remark field is set.
       */
      public boolean hasRemark() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>required string remark = 9;</code>
       * @return The remark.
       */
      public String getRemark() {
        Object ref = remark_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            remark_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>required string remark = 9;</code>
       * @return The bytes for remark.
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>required string remark = 9;</code>
       * @param value The remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemark(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>required string remark = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemark() {
        bitField0_ = (bitField0_ & ~0x00000100);
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>required string remark = 9;</code>
       * @param value The bytes for remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        remark_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SharedbikeArea)
    }

    // @@protoc_insertion_point(class_scope:SharedbikeArea)
    private static final SharedbikeArea DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SharedbikeArea();
    }

    public static SharedbikeArea getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<SharedbikeArea>
        PARSER = new com.google.protobuf.AbstractParser<SharedbikeArea>() {
      @Override
      public SharedbikeArea parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SharedbikeArea(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SharedbikeArea> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SharedbikeArea> getParserForType() {
      return PARSER;
    }

    @Override
    public SharedbikeArea getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SharedbikeArea_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SharedbikeArea_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024SharedbikeArea.proto\"\221\001\n\016SharedbikeAre" +
      "a\022\016\n\006areaId\030\001 \002(\r\022\014\n\004name\030\002 \002(\t\022\013\n\003lng\030\003" +
      " \002(\001\022\013\n\003lat\030\004 \002(\001\022\014\n\004size\030\005 \002(\001\022\014\n\004type\030" +
      "\006 \002(\r\022\016\n\006maxNum\030\007 \002(\r\022\013\n\003num\030\010 \002(\r\022\016\n\006re" +
      "mark\030\t \002(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SharedbikeArea_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SharedbikeArea_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SharedbikeArea_descriptor,
        new String[] { "AreaId", "Name", "Lng", "Lat", "Size", "Type", "MaxNum", "Num", "Remark", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
